"""
Django settings for proyectoasw project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import dj_database_url
from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# Hay que modificarla
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "True"

# Se usa al querer hacer deploy
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS").split(" ")


# Application definition

SITE_ID = 4

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #Apps Propias
    #'AppASW.apps.AppaswConfig'
    
    "AppASW",
    #google-auth
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile", 
            "email"
        ],
        "AUTH_PARAMS": {"access_type": "online"}
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'proyectoasw.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyectoasw.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

database_url = os.environ.get("DATABASE_URL")
DATABASES['default'] = dj_database_url.parse(database_url)

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

AWS_ACCESS_KEY_ID = 'ASIAVRUVVTLOYGNJ4JWH'
AWS_SECRET_ACCESS_KEY = 'SPlAlaVyw01lJfheNolonVlMvvE9DDjFUAnZE+BW'
AWS_SESSION_TOKEN = 'IQoJb3JpZ2luX2VjEKH//////////wEaCXVzLXdlc3QtMiJHMEUCIHQbBWy2msEJ5kw5laD/xOUNevJ5jeVugZWXvgzhlZ4QAiEAtbEq0r32gYGKiPVHUFTBz12ff5j1Q1yd/T85AjZ1j9gqwgII2v//////////ARAAGgwzODE0OTIyMzkwNjkiDBDCYtpyj4RLRd2i2yqWAjgif75ZJs2r7D5kAB5u9yHEGAVDg9G9pAazwHNY7NF1e88hwdooASC5jw7ec9dPQ7OFwzz+dG34EvpFzUri67uPNzt5neR4bwEVAKAs0nYwJ1haFLOL9oBTU99Mr7r18Cccgl4GXbxYmVNz9PB+TxlzaU8Nq1lT8vU5DK8wsndQg0NUCn9VxMO4bdjESnkNk0muJbTkQMleaN7HrTWZ2xwKjEJBw2CVkApQ8sSWOt1UbNei9TyJz1f2OY2tYt4IskaEkMH6aNV11KB5gA0HDQEDLTajxxlZFyWUYkin4IOvV5ee2bSeW5uOlxtJpWl3b3eOEzxXsr9ftocMQAP0CO5YnbVwCYiZPoRT196r/diyun91g9GgMOaAgLEGOp0BA2lUdo8NmPbnTQ962lfpTCd0Bi+Abkw4ZlBnk4dzSgl3ccBaDEZRqb4b/PJov0cGj5MMKch89QiulriagoF87jkqCbEyAZSAk+/gXl4v4Qkmjj7xSuR4t9bNUt5zHC0+2gVaSgXmKJ/NnuYiix973BNKVgc3998WlSqfhoVe1jmODPostBU3lNfmW5fdB725AumfJocvUz6OyZUw8A=='
AWS_STORAGE_BUCKET_NAME = 'kbinsocialbucket'
AWS_S3_SIGNATURE_NAME = 's3v4',
AWS_S3_REGION_NAME = 'us-east-1'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL =  None
AWS_S3_VERIFY = True
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'